# kp/management/commands/seed_kp.py
from __future__ import annotations

import os
import random
from datetime import timedelta
from pathlib import Path
from django.core.management.base import BaseCommand
from django.contrib.auth import get_user_model
from django.db import transaction
from django.conf import settings
from django.utils import timezone

from kp.models import EventType, KPTemplate, Proposal, ProposalItem
from catalog.models import Service


User = get_user_model()


def _ensure_dir(path: str) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)


def _list_media_files(rel_dir: str) -> list[str]:
    media_root = Path(getattr(settings, "MEDIA_ROOT", "") or "")
    if not media_root:
        return []
    base = media_root / rel_dir
    if not base.exists():
        return []
    files = [p for p in base.rglob("*") if p.is_file()]
    files.sort()
    return [str(p.relative_to(media_root)).replace("\\", "/") for p in files]


def _try_make_kp_photo(rel_path: str, title: str) -> str | None:
    try:
        from PIL import Image, ImageDraw  # type: ignore
    except Exception:
        return None

    media_root = getattr(settings, "MEDIA_ROOT", None)
    if not media_root:
        return None

    abs_path = os.path.join(media_root, rel_path)
    _ensure_dir(abs_path)

    img = Image.new("RGB", (1200, 700), (18, 18, 22))
    draw = ImageDraw.Draw(img)

    draw.rounded_rectangle([40, 40, 1160, 660], radius=46, outline=(110, 110, 135), width=6)
    draw.text((80, 90), "KP COVER", fill=(240, 240, 245))
    draw.text((80, 150), title[:36], fill=(200, 200, 220))
    draw.text((80, 210), "generated by seed", fill=(160, 160, 180))

    img.save(abs_path, format="PNG")
    return rel_path


class Command(BaseCommand):
    help = "Seed KP: event types, templates, proposals, items (plus optional proposal cover photos)."

    def add_arguments(self, parser):
        parser.add_argument("--seed", type=int, default=42)
        parser.add_argument("--templates", type=int, default=4)
        parser.add_argument("--proposals", type=int, default=35)
        parser.add_argument("--items-min", type=int, default=3)
        parser.add_argument("--items-max", type=int, default=9)
        parser.add_argument("--with-photos", action="store_true")
        parser.add_argument("--clear", action="store_true")

    @transaction.atomic
    def handle(self, *args, **opts):
        rnd = random.Random(opts["seed"])

        if opts["clear"]:
            ProposalItem.objects.all().delete()
            Proposal.objects.all().delete()
            KPTemplate.objects.all().delete()
            EventType.objects.all().delete()
            self.stdout.write(self.style.WARNING("kp: cleared"))

        admin = User.objects.filter(is_superuser=True).first()
        if not admin:
            self.stdout.write(self.style.ERROR("kp: no superuser. Run seed_accounts first."))
            return

        customers = list(User.objects.filter(is_superuser=False, is_staff=False)[:200])
        if not customers:
            customers = [admin]

        # Event types
        event_types = []
        for name in ["Свадьба", "Корпоратив", "День рождения", "Открытие", "Промо"]:
            et, _ = EventType.objects.get_or_create(name=name, defaults={"is_active": True})
            event_types.append(et)

        # Templates
        templates_n = int(opts["templates"])
        templates = []
        colors = [
            ("#6D28D9", "#1E3A8A"),
            ("#047857", "#0F766E"),
            ("#B45309", "#7C2D12"),
            ("#BE123C", "#9F1239"),
            ("#0E7490", "#1D4ED8"),
        ]
        font_pool = ["Inter", "Manrope", "Montserrat", "Lora", "PT Sans"]
        for i in range(templates_n):
            et = rnd.choice(event_types)
            p_color, s_color = colors[i % len(colors)]
            t, _ = KPTemplate.objects.get_or_create(
                name=f"Шаблон сметы (seed) #{i+1}",
                event_type=et,
                defaults={
                    "show_cover": True,
                    "show_intro": True,
                    "show_gift": True,
                    "show_footer": True,
                    "intro_title": "О наших услугах",
                    "intro_subtitle": "Демо-текст. Здесь будет краткое описание того, что вы предлагаете клиенту.",
                    "gift_text": "{client_name}, заберите ваш индивидуальный подарок!",
                    "gift_button_text": "Забрать подарок",
                    "gift_button_url": "https://2gis.kz/almaty",
                    "footer_text": "Спасибо за доверие. По вопросам — свяжитесь с нами в WhatsApp",
                    "footer_copyright": "AE",
                    "primary_color": p_color,
                    "secondary_color": s_color,
                    "font_family": font_pool[i % len(font_pool)],
                },
            )
            templates.append(t)

        services = list(Service.objects.filter(is_active=True))
        if not services:
            self.stdout.write(self.style.ERROR("kp: no services. Run seed_catalog first."))
            return

        proposals_n = int(opts["proposals"])
        items_min = int(opts["items_min"])
        items_max = int(opts["items_max"])
        with_photos = bool(opts["with_photos"])
        photo_pool = _list_media_files("seed/kp/photos")
        if items_min > items_max:
            items_min, items_max = items_max, items_min

        created_items = 0

        for n in range(proposals_n):
            customer = rnd.choice(customers)
            tpl = rnd.choice(templates)

            dt = timezone.now() + timedelta(days=rnd.randrange(1, 90), hours=rnd.randrange(0, 23))
            title = f"Смета для {customer.username} #{n+1}"
            status_pool = [
                Proposal.Status.DRAFT,
                Proposal.Status.DRAFT,
                Proposal.Status.DRAFT,
                Proposal.Status.REQUESTED,
                Proposal.Status.SENT,
                Proposal.Status.CONFIRMED,
                Proposal.Status.REJECTED,
                Proposal.Status.POSTPONED,
            ]

            kp = Proposal.objects.create(
                owner=admin,
                customer=customer,
                template=tpl,
                title=title,
                status=rnd.choice(status_pool),
                notes="",
                event_title=rnd.choice(["Свадьба", "Корпоратив", "ДР", "Презентация", "Открытие"]),
                event_datetime=dt,
                event_location=rnd.choice(["Алматы", "Астана", "Шымкент", "Тараз", "Онлайн"]),
                event_description="Сгенерировано сидером. Демо-описание, чтобы не было пусто.",
                drive_link=rnd.choice([
                    "https://toolgiz.com",
                    "https://2gis.kz/almaty",
                    "https://meet.google.com/landing",
                    "",
                ]),
            )

            if with_photos and not kp.photo:
                rel = photo_pool[n % len(photo_pool)] if photo_pool else None
                made = rel or _try_make_kp_photo(f"seed/kp/photos/{kp.id}.png", kp.title)
                if made:
                    kp.photo = made
                    kp.save(update_fields=["photo"])

            # items
            k = rnd.randrange(items_min, items_max + 1)
            picked = rnd.sample(services, k=min(k, len(services)))

            for svc in picked:
                qty = rnd.randrange(1, 4)
                price = getattr(svc, "base_price", 0) or 0

                ProposalItem.objects.create(
                    proposal=kp,
                    service=svc,
                    qty=qty,
                    price=price,
                    discount=0,
                    comment=rnd.choice(["", "включено", "как на фото", "пакет PRO"]),
                )
                created_items += 1

        self.stdout.write(self.style.SUCCESS(
            f"kp: done. templates={templates_n}, proposals={proposals_n}, items={created_items}, photos={'yes' if with_photos else 'no'}"
        ))
