# Generated by Django 4.2.19 on 2026-01-07 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='KPTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('show_cover', models.BooleanField(default=True)),
                ('show_intro', models.BooleanField(default=True)),
                ('show_gift', models.BooleanField(default=True)),
                ('show_footer', models.BooleanField(default=True)),
                ('intro_title', models.CharField(blank=True, default='О наших услугах', max_length=160)),
                ('intro_subtitle', models.TextField(blank=True, default='')),
                ('gift_text', models.CharField(blank=True, default='{client_name}, заберите ваш индивидуальный подарок!', max_length=220)),
                ('gift_button_text', models.CharField(blank=True, default='Забрать подарок', max_length=80)),
                ('gift_button_url', models.URLField(blank=True, default='')),
                ('footer_text', models.TextField(blank=True, default='Спасибо за доверие. По вопросам — свяжитесь с нами в WhatsApp')),
                ('footer_copyright', models.CharField(blank=True, default='', max_length=120)),
                ('primary_color', models.CharField(blank=True, default='#6D28D9', max_length=16)),
                ('secondary_color', models.CharField(blank=True, default='#1E3A8A', max_length=16)),
                ('font_family', models.CharField(blank=True, default='Inter', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='kp.eventtype')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('REQUESTED', 'Запрос (клиент → менеджеру)'), ('SENT', 'Отправлено/архив'), ('CONFIRMED', 'Подтверждено'), ('REJECTED', 'Отклонено'), ('POSTPONED', 'Перенесено')], default='DRAFT', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('event_title', models.CharField(blank=True, default='', max_length=200)),
                ('event_datetime', models.DateTimeField(blank=True, null=True)),
                ('event_location', models.CharField(blank=True, default='', max_length=240)),
                ('event_description', models.TextField(blank=True, default='')),
                ('drive_link', models.URLField(blank=True, default='')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='kp/photos/')),
                ('template_snapshot', models.JSONField(blank=True, null=True)),
                ('public_token', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_proposals', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='kp.kptemplate')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProposalItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('comment', models.CharField(blank=True, default='', max_length=240)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='kp.proposal')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.service')),
            ],
            options={
                'indexes': [models.Index(fields=['proposal'], name='kp_proposal_proposa_d84c34_idx'), models.Index(fields=['service'], name='kp_proposal_service_1f5abe_idx')],
                'unique_together': {('proposal', 'service')},
            },
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['customer', 'status', '-updated_at'], name='kp_proposal_custome_d36980_idx'),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['public_token'], name='kp_proposal_public__faca88_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='kptemplate',
            unique_together={('event_type', 'name')},
        ),
    ]
