# Generated by Django 5.2.10 on 2026-01-12 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='fixed_extra',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='fixed_subtotal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='fixed_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
