# Generated by Django 4.2.19 on 2026-01-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='allow_multiple',
            field=models.BooleanField(default=True, help_text='Если выключено — услугу можно добавить в КП только один раз (qty всегда = 1).', verbose_name='Повторяемая (можно несколько раз)'),
        ),
    ]
