# Generated by Django 5.2.10 on 2026-01-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_service_allow_multiple'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='instagram_url',
            field=models.URLField(blank=True, default='', help_text='Ссылка на Instagram (пример: https://instagram.com/...)', verbose_name='Instagram ссылка'),
        ),
    ]
