# Generated by Django 5.2.10 on 2026-01-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_service_instagram_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='Описание (EN)'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_kk',
            field=models.TextField(blank=True, default='', verbose_name='Описание (KZ)'),
        ),
        migrations.AddField(
            model_name='category',
            name='description_ru',
            field=models.TextField(blank=True, default='', verbose_name='Описание (RU)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Название (EN)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_kk',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Название (KZ)'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(default='', max_length=255, verbose_name='Название (RU)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='Описание (EN)'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_kk',
            field=models.TextField(blank=True, default='', verbose_name='Описание (KZ)'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_ru',
            field=models.TextField(blank=True, default='', verbose_name='Описание (RU)'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Название (EN)'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_kk',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Название (KZ)'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_ru',
            field=models.CharField(default='', max_length=255, verbose_name='Название (RU)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='allow_multiple',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='instagram_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
