# Generated by Django 5.2.10 on 2026-02-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_service_image_2_service_image_3_service_youtube_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
        migrations.AddField(
            model_name='service',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
        migrations.AddField(
            model_name='service',
            name='image_6',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
    ]
