# Generated by Django 5.2.10 on 2026-01-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(blank=True, max_length=255, verbose_name='Компания'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='user',
            name='sphere',
            field=models.CharField(blank=True, max_length=255, verbose_name='Сфера'),
        ),
        migrations.AddField(
            model_name='user',
            name='tags_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram',
            field=models.CharField(blank=True, max_length=64, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=32, verbose_name='WhatsApp'),
        ),
    ]
