# Generated by Django 5.2.10 on 2026-02-18 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.CharField(max_length=255, verbose_name='Заголовок (RU)')),
                ('title_kk', models.CharField(blank=True, default='', max_length=255, verbose_name='Заголовок (KZ)')),
                ('title_en', models.CharField(blank=True, default='', max_length=255, verbose_name='Заголовок (EN)')),
                ('description_ru', models.TextField(blank=True, default='', verbose_name='Описание (RU)')),
                ('description_kk', models.TextField(blank=True, default='', verbose_name='Описание (KZ)')),
                ('description_en', models.TextField(blank=True, default='', verbose_name='Описание (EN)')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='portfolio/covers/', verbose_name='Обложка')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Кейс',
                'verbose_name_plural': 'Кейсы',
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ru', models.CharField(max_length=255, verbose_name='Название (RU)')),
                ('name_kk', models.CharField(blank=True, default='', max_length=255, verbose_name='Название (KZ)')),
                ('name_en', models.CharField(blank=True, default='', max_length=255, verbose_name='Название (EN)')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioCasePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/photos/', verbose_name='Фото')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='portfolio.portfoliocase', verbose_name='Кейс')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='portfoliocase',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='portfolio.portfoliocategory', verbose_name='Категория'),
        ),
    ]
